### ISSUE TITLE
Not Work

### ISSUE THREAD

**Issue by xone0** [codebuglab/laravel-go-translate#1]
php artisan go-translate:resource de es this work not why ?

**Comment by moelkomy** [comment]
Did you set the source and destination language?
For example, if your main language files are English and you want to translate them to Spanish you have to be sure about the following.

1- You have a folder `en` inside `/resources/lang`.
2- You have PHP language files as a normal Laravel project in `en` folder.
2- Your command is like this `php artisan go-translate:resource en es`.

If it still doesn't work please give us your response error, screenshot, or a video from your side.

I'm waiting to hear from you, whether it worked or not.
