### ISSUE TITLE
.mp4 files not being supported

### ISSUE THREAD

**Issue by abzzzmedia** [codebuglab/laravel-go-translate#2]
Hello, i've tried this but when i tried to translate the .mp4 files it told me that We don't support this extension for this file '.mp4 " 

Is there any way that it can work with .mp4 files ?

**Comment by moelkomy** [comment]
Hello, @abzzzmedia 

Sorry, but this package only translates PHP and JSON files in Laravel projects.

And .mp4 is a video extension that makes me wonder what you want to do.
